<?php
const CONSUMER_KEY = '2F5kJYqkGzTYb5YRgDq8bxZys';
const CONSUMER_SECRET = 'HV6KGVJgeqC9C4fNUxkCZKs4XrDCrGSJFLhq4h4ABzwmGFzTXY';
const ACCESS_TOKEN = 'VQDhnW6ezGhbg9fBm4zc9-sSpU2nDh2Mg4Xz6YnXSeDBVFrgsS';
const ACCESS_TOKEN_SECRET = 'FEtEqBpgLawCHnu75LrSBLs7sDqTXHZMXA83jNwNnf9ea';